default_output_dir: "surface_results"
metrics_format: ["csv", "json"]
save_side_by_side: False


ground_truth:
    base_path: "dataset/"
    classes:
      - name: "brick_cracks"
        dir: brick_cracks
      - name: "concrete_cracks"
        dir: concrete_cracks
      - name: "no_defects"
        dir: nodefects
        invert: True


instruments:
  - name: "CrackDenseLinkNet"
    predictions_path: results/crackdenselinknet/

  - name: "Crack Segmentation with Super-Resolution (CSSR)"
    predictions_path: results/cssr/

  - name: "Hierarchical Multi-Scale Attention (HMA)"
    predictions_path: results/processed_hma/

  - name: "Global classification and segmentation"
    predictions_path: results/sccdnet/


